done 1 task
js-tasks-ru/jsbasic-20231211_amineva-mira pull request #11
Opened 2024-01-16 18:20 UTC by thonngo

2024-01-17 15:54 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-17 17:11 UTC, koalex requested changes
Исправить замечания в **6-1**

2024-01-17 17:11 UTC, koalex commented on 6-module/1-task/index.js
> +    document.body.append(this.elem);
Эта строка лишняя

2024-01-17 17:11 UTC, koalex commented on 6-module/1-task/index.js
> +    this.tbodyTable=document.querySelector('.rows');
Здесь надо исправить на 
`this.tbodyTable = this.elem.querySelector('.rows');`

2024-01-18 14:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-18 17:26 UTC, koalex requested changes
Нужно решить **6-3**

2024-01-18 17:27 UTC, koalex commented
> Нужно решить **6-3**

напишите мне в Discord если не получается решить

2024-01-18 17:27 UTC, closed without merging